#define MOTOR_KV 3600
#define GEAR_RATIO 30
#define MIN_VOLTAGE 6

#define MAX_VELOCITY 0.003

#define RIGHT_MOTOR_PIN_1 7
#define RIGHT_MOTOR_PIN_2 6
#define RIGHT_MOTOR_PIN_PWM 5

#define RIGHT_ENCODER_PIN_A 0
#define RIGHT_ENCODER_PIN_B 2

#define LEFT_MOTOR_PIN_1 11
#define LEFT_MOTOR_PIN_2 10
#define LEFT_MOTOR_PIN_PWM 9

#define LEFT_ENCODER_PIN_A 3
#define LEFT_ENCODER_PIN_B 1

#define ENCODER_TICKS_PER_ROTATION 12

#define MOTOR_VEL_PID_P 200
#define MOTOR_VEL_PID_I 0
#define MOTOR_VEL_PID_D 0
#define MOTOR_VEL_PID_F 255

#define ENCODER_TICKS_PER_WHEEL_ROTATION 360
#define WHEEL_TRACK 113.66
#define WHEEL_DIAMETER 30
