#define MOTOR_KV 3600
#define GEAR_RATIO 30
#define MIN_VOLTAGE 6

#define MAX_VELOCITY 0.0055

#define RIGHT_MOTOR_PIN_1 16
#define RIGHT_MOTOR_PIN_2 15
#define RIGHT_MOTOR_PIN_PWM 18

#define RIGHT_ENCODER_PIN_A 2
#define RIGHT_ENCODER_PIN_B 3

#define LEFT_MOTOR_PIN_1 16
#define LEFT_MOTOR_PIN_2 15
#define LEFT_MOTOR_PIN_PWM 18

#define LEFT_ENCODER_PIN_A 2
#define LEFT_ENCODER_PIN_B 3

#define ENCODER_TICKS_PER_ROTATION 12

#define MOTOR_VEL_PID_P 0
#define MOTOR_VEL_PID_I 0
#define MOTOR_VEL_PID_D 0
#define MOTOR_VEL_PID_F 255

#define ENCODER_TICKS_PER_WHEEL_ROTATION 360
#define WHEEL_TRACK 3.4
#define WHEEL_DIAMETER 3.4
