#define MOTOR_KV 3600
#define GEAR_RATIO 30
#define MIN_VOLTAGE 6

#define MAX_VELOCITY 0.0055

#define MOTOR_PIN_1 16
#define MOTOR_PIN_2 15
#define MOTOR_PIN_PWM 18

#define ENCODER_PIN_A 2
#define ENCODER_PIN_B 3
#define ENCODER_TICKS_PER_ROTATION 12


#define MOTOR_VEL_PID_P 0
#define MOTOR_VEL_PID_I 0
#define MOTOR_VEL_PID_D 0
#define MOTOR_VEL_PID_F 255
